/**
 * 业务错误码 — 提供给 agent 决策用的稳定枚举。
 * 命名规则：大写下划线，前缀按域分组。
 */
export enum ErrorCode {
  // 通用
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RATE_LIMITED = 'RATE_LIMITED',
  TIMEOUT = 'TIMEOUT',
  NOT_FOUND = 'NOT_FOUND',

  // 浏览器/抓取
  BROWSER_LAUNCH_FAILED = 'BROWSER_LAUNCH_FAILED',
  NAVIGATION_FAILED = 'NAVIGATION_FAILED',

  // 登录态
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  LOGIN_TIMEOUT = 'LOGIN_TIMEOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',

  // 小红书域
  XHS_TARGET_NOT_FOUND = 'XHS_TARGET_NOT_FOUND',
  XHS_BLOCKED = 'XHS_BLOCKED',
  XHS_PARSE_FAILED = 'XHS_PARSE_FAILED',

  // 抖音域
  DOUYIN_TARGET_NOT_FOUND = 'DOUYIN_TARGET_NOT_FOUND',
  DOUYIN_BLOCKED = 'DOUYIN_BLOCKED',
  DOUYIN_CAPTCHA = 'DOUYIN_CAPTCHA',
  DOUYIN_PARSE_FAILED = 'DOUYIN_PARSE_FAILED',

  // 存储
  STORAGE_READ_FAILED = 'STORAGE_READ_FAILED',
  STORAGE_PATH_FORBIDDEN = 'STORAGE_PATH_FORBIDDEN',
}

export const ERROR_CODE_TO_HTTP: Record<ErrorCode, number> = {
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.TIMEOUT]: 504,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.BROWSER_LAUNCH_FAILED]: 503,
  [ErrorCode.NAVIGATION_FAILED]: 502,
  [ErrorCode.LOGIN_REQUIRED]: 401,
  [ErrorCode.LOGIN_TIMEOUT]: 408,
  [ErrorCode.LOGIN_FAILED]: 401,
  [ErrorCode.XHS_TARGET_NOT_FOUND]: 404,
  [ErrorCode.XHS_BLOCKED]: 451,
  [ErrorCode.XHS_PARSE_FAILED]: 422,
  [ErrorCode.DOUYIN_TARGET_NOT_FOUND]: 404,
  [ErrorCode.DOUYIN_BLOCKED]: 451,
  [ErrorCode.DOUYIN_CAPTCHA]: 451,
  [ErrorCode.DOUYIN_PARSE_FAILED]: 422,
  [ErrorCode.STORAGE_READ_FAILED]: 500,
  [ErrorCode.STORAGE_PATH_FORBIDDEN]: 403,
};
