#!/usr/bin/env bash
# 根据当前工作区生成绝对路径版 mcp.json（兼容不支持 ${workspaceFolder} 的 OpenClaw 版本）。
# 用法：
#   bash .openclaw/mcp.absolute.generate.sh                 # 写入 .openclaw/mcp.absolute.json
#   bash .openclaw/mcp.absolute.generate.sh --to-home       # 同时同步到 ~/.openclaw/mcp.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${SCRIPT_DIR}/mcp.absolute.json"

cat > "${OUT}" <<JSON
{
  "_comment": "auto-generated by .openclaw/mcp.absolute.generate.sh on $(date -Iseconds)",
  "mcpServers": {
    "supercrawler": {
      "command": "node",
      "args": ["${ROOT}/dist/mcp/mcp.stdio.js"],
      "cwd": "${ROOT}",
      "env": {
        "PROFILE_DIR": "${ROOT}/data/profiles",
        "OUTPUT_DIR": "${ROOT}/data/output",
        "CLOAK_HEADLESS": "true",
        "CLOAK_TIMEZONE": "Asia/Shanghai",
        "CLOAK_LOCALE": "zh-CN",
        "XHS_SCRAPE_CONCURRENCY": "1",
        "LOG_LEVEL": "warn"
      }
    }
  }
}
JSON

echo "✅ 已生成: ${OUT}"

if [[ "${1:-}" == "--to-home" ]]; then
  mkdir -p "${HOME}/.openclaw"
  cp "${OUT}" "${HOME}/.openclaw/mcp.json"
  echo "✅ 已同步到: ${HOME}/.openclaw/mcp.json"
fi
